// Azure Developer CLI (azd) main Bicep template.
// Deploys the project-scaffold Node.js/Express app to Azure App Service
// with a system-assigned managed identity and Application Insights.

@description('The location for the resource group. Automatically generated by azd.')
param location string = resourceGroup().location

@description('The name of the application environment. Automatically generated by azd.')
param environmentName string

@description('Name of the Application Insights resource.')
param applicationInsightsName string = ''

@description('Name of the App Service Plan resource.')
param appServicePlanName string = ''

@description('Name of the App Service resource.')
param appServiceName string = ''

@description('The SKU/tier for the App Service Plan.')
param appServicePlanSku string = 'B1'

@description('The instance size for the App Service Plan.')
param appServicePlanSize string = 'B1'

@description('The name of the log analytics workspace.')
param logAnalyticsName string = ''

var appInsightsName = (applicationInsightsName == '') ? '${environmentName}-appinsights' : applicationInsightsName
var appServicePlanName = (appServicePlanName == '') ? '${environmentName}-plan' : appServicePlanName
var appServiceName = (appServiceName == '') ? '${environmentName}-web' : appServiceName
var logAnalyticsWorkspaceName = (logAnalyticsName == '') ? '${environmentName}-logs' : logAnalyticsName

// Log Analytics workspace for Application Insights
resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: logAnalyticsWorkspaceName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
  }
}

// Application Insights for monitoring
resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalyticsWorkspace.id
  }
}

// App Service Plan
resource appServicePlan 'Microsoft.Web/serverfarms@2022-09-01' = {
  name: appServicePlanName
  location: location
  sku: {
    name: appServicePlanSku
    tier: 'Basic'
    size: appServicePlanSize
    family: 'B'
    capacity: 1
  }
  properties: {
    reserved: true
  }
}

// App Service (the web app) with system-assigned managed identity
resource appService 'Microsoft.Web/sites@2022-09-01' = {
  name: appServiceName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    siteConfig: {
      linuxFxVersion: 'NODE|20-lts'
      appSettings: [
        {
          name: 'APP_NAME'
          value: 'project-scaffold'
        }
        {
          name: 'DEBUG'
          value: 'false'
        }
        {
          name: 'PORT'
          value: '8000'
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: applicationInsights.properties.ConnectionString
        }
        {
          name: 'SCM_DO_BUILD_DURING_DEPLOYMENT'
          value: 'true'
        }
      ]
    }
  }
}

output APPLICATIONINSIGHTS_CONNECTION_STRING string = applicationInsights.properties.ConnectionString
output APP_SERVICE_NAME string = appService.name
output APP_SERVICE_URL string = 'https://${appService.properties.defaultHostName}'
output APP_SERVICE_PLAN_NAME string = appServicePlan.name
output LOG_ANALYTICS_WORKSPACE_NAME string = logAnalyticsWorkspace.name
